### ISSUE TITLE
Relying on the printing of the method table is brittle

### ISSUE THREAD

**Issue by KristofferC** [madsjulia/DocumentFunction.jl#6]
The tests for this package fails on the upcoming 1.9 due to changes in how methods is printed which means that https://github.com/madsjulia/DocumentFunction.jl/blob/2e5344f852e94a8bfb6b283dd257d1fa4d0800af/src/DocumentFunction.jl#L27 is no longer accurate.

Relying on the exact way things are printed in Base is brittle because it might change from version to version.

**Comment by montyvesselinov** [comment]
Thank you! This has been partially fixed in the latest version.
